version: 2

before:
  hooks:
  # You may remove this if you don't use go modules.
  - go mod tidy
  # This ensures that all dependencies are downloaded before building.
  - go mod download

builds:
- env:
  # CGO is disabled to ensure statically linked binaries for portability across systems.
  - CGO_ENABLED=0
  binary: "{{ .ProjectName }}"
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: windows
    goarch: arm64
  ldflags:
  - "-s -w -X tfrun/cmd/tfrun.version={{ .Version }} -X tfrun/cmd/tfrun.commit={{ .Commit }} -X tfrun/cmd/tfrun.date={{ .Date }}"

archives:
- name_template: >-
    {{ .ProjectName }}_ {{- .Version }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end }}
  files:
  - LICENSE
  - README.md

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: rajamohan-rj
    name: tfrun
  draft: false
  prerelease: auto
  mode: replace

# Homebrew formula configuration
brews:
- name: tfrun
  repository:
    owner: rajamohan-rj
    name: homebrew-tap
    branch: main
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  directory: Formula
  homepage: "https://github.com/rajamohan-rj/tfrun"
  description: "Git-aware Terraform runner"
  license: "MIT"
  install: |
    bin.install "tfrun" => "tfrun"
  test: |
    system "#{bin}/tfrun", "--version"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - "README"
  groups:
  - title: Features
    regexp: "^.*feat[(\\w)]*:+.*$"
    order: 0
  - title: 'Bug fixes'
    regexp: "^.*fix[(\\w)]*:+.*$"
    order: 1
  - title: Others
    order: 999
